// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8pY6O3xqpxdG9wH5WWbGrJab549-CNJE',
    appId: '1:49144889203:web:54d9d38c044bc24039cf06',
    messagingSenderId: '49144889203',
    projectId: 'intro-mobile',
    authDomain: 'intro-mobile.firebaseapp.com',
    storageBucket: 'intro-mobile.appspot.com',
    measurementId: 'G-6N583026Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3GdwVcUmqjCH_hBJ5CaK_DuYYl4SmS60',
    appId: '1:49144889203:android:149a96a3577c877139cf06',
    messagingSenderId: '49144889203',
    projectId: 'intro-mobile',
    storageBucket: 'intro-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE49NqR_04-glVbLj8mOFrc8KKXWbdLeM',
    appId: '1:49144889203:ios:f1ec953889722e7239cf06',
    messagingSenderId: '49144889203',
    projectId: 'intro-mobile',
    storageBucket: 'intro-mobile.appspot.com',
    iosClientId: '49144889203-f8tav8kj7srk98tirijpabicbn7e7eqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
